#!/usr/bin/env bash

# $0 is part of POSIX specific whereas BASH_SOURCE is bash specific.
# echo "[$0] vs. [${BASH_SOURCE[0]}]"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd )"

# warning for move forward
printf "This will overwrite all your dotfiles if you agree type \"yes\": ";
read choice

if [[ "$choice" != "yes" ]]
#    ^         ^  ^     ^           spaces are needed
then
    echo "install script is cancelled"
    exit 1
fi

mkdir -p $HOME/.config/nvim
ln -f -s ${BASEDIR}/.config/nvim/init.vim $HOME/.config/nvim/init.vim
ln -f -s ${BASEDIR}/.bashrc $HOME/.bashrc
ln -f -s ${BASEDIR}/.zshrc $HOME/.zshrc
ln -f -s ${BASEDIR}/.zprofile $HOME/.zprofile
ln -f -s ${BASEDIR}/.profile $HOME/.zprofile

mkdir -p $HOME/.local/bin
mkdir -p $HOME/.local/share
cp -r ${BASEDIR}/.local/bin/* $HOME/.local/bin
cp -r ${BASEDIR}/.local/share/* $HOME/.local/share
